# Generated by Django 3.1.6 on 2021-02-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('selection', models.CharField(choices=[['happy', 'happy'], ['sadness', 'sadness'], ['horror', 'horror'], ['SF', 'SF'], ['other', 'other']], max_length=7)),
            ],
        ),
    ]
